[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  # Proxy all API requests to Render backend
  from = "/api/*"
  to = "https://pos-backend-0fji.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  # Let Next.js handle all other routes
  from = "/*"
  to = "/index.html"
  status = 200
